# Generated by Django 6.1 on 2026-09-08 12:15

import django.db.models.deletion
import recipes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titlu rețetă')),
                ('description', models.TextField(help_text='Scrie aici ingredientele și modul de preparare al rețetei.', verbose_name='Descriere și pași preparare')),
                ('category', models.CharField(choices=[('mic_dejun', 'Mic dejun'), ('ciorbe', 'Ciorbe / Supe'), ('fel_principal', 'Fel principal'), ('desert', 'Desert'), ('patiserie', 'Patiserie'), ('panificatie', 'Panificație')], default='Fel principal', max_length=20, verbose_name='Categorie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dată creare')),
                ('cooking_time', models.PositiveIntegerField(default=30, help_text='Introdu timpul total exprimat în minute.', verbose_name='Timp de gătire (minute)')),
                ('imagine_prezentare', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(recipes.models.get_default_superuser), related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rețetă',
                'verbose_name_plural': 'Rețete',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(recipes.models.get_default_superuser), related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.recipe')),
            ],
        ),
    ]
