# Generated by Django 6.1 on 2026-08-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titlu rețetă')),
                ('description', models.TextField(help_text='Scrie aici ingredientele și modul de preparare al rețetei.', verbose_name='Descriere și pași preparare')),
                ('category', models.CharField(choices=[('ciorbe', 'Ciorbe / Supe'), ('desert', 'Desert'), ('fel_principal', 'Fel principal'), ('patiserie', 'Patiserie')], default='Fel principal', max_length=20, verbose_name='Categorie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dată creare')),
                ('cooking_time', models.PositiveIntegerField(default=30, help_text='Introdu timpul total exprimat în minute', verbose_name='Timp de gătire (minute)')),
            ],
        ),
    ]
