# Generated by Django 6.1 on 2026-08-24 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('mic_dejun', 'Mic dejun'), ('ciorbe', 'Ciorbe / Supe'), ('fel_principal', 'Fel principal'), ('desert', 'Desert'), ('patiserie', 'Patiserie'), ('panificatie', 'Panificație')], default='Fel principal', max_length=20, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(default=30, help_text='Introdu timpul total exprimat în minute.', verbose_name='Timp de gătire (minute)'),
        ),
    ]
