# Generated by Django 6.1 on 2026-08-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_category_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Rețetă', 'verbose_name_plural': 'Rețete'},
        ),
    ]
