# Generated by Django 6.1 on 2026-08-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
