# Generated by Django 6.1 on 2026-08-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='cover_image',
            new_name='imagine_prezentare',
        ),
    ]
